### ISSUE TITLE
Fix config.h version number

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#10]
Tools expect to parse this out and ours just contains "todo".

We'll probably do this in the build script, and check in config.h for cases where git can't be queried, like on crates.io:

- Teach the build script how to construct the same version info as the binaryen config script does
- Generate config.h in memory
- Compare it to the existing config.h in wasm-opt/src/config.h
- If they are different, write the new one.

**Comment by Aimeedeer** [comment]
done
