### ISSUE TITLE
Avoid string copies in shims

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#107]
There's a better pattern for moving strings across the FFI instead of copying them.

It doesn't much that we're copying when we don't have to, but when we get the opportunity for breaking changes, we might as well make the code a bit more correct.

Need to wait for a major version bump.

From https://github.com/brson/wasm-opt-rs/issues/95

> Yep, and the way to avoid a copy is by passing Pin<&mut CxxString> from Rust to C++, receiving it as std::string&, and calling std::move. let_cxx_string! (which you are already using) produces a local binding of type Pin<&mut CxxString>, so the deref from that to &CxxString in your Rust code is what forces a copy to be done afterward in C++.

**Comment by Aimeedeer** [comment]
Fixed https://github.com/brson/wasm-opt-rs/pull/120
