### ISSUE TITLE
CI matrix is not quite right

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#118]
Here's a recent run: https://github.com/brson/wasm-opt-rs/actions/runs/3340000843/jobs/5529605541

The intent is to run three windows builds: stable, 1.48, and stable+32-bit. The stable+64-bit build is not running though. The build labeled `windows-2019, stable' is running the `build / test 32-bit case`.

This is probably true of several of the combinations under the "include" matrix section - they are conflicting in some way with the 'os' and 'rust' matrix specs. I don't know how github ci works enough to know what's going on right away, but maybe we need matrix entries for things like 'target', 'c-compiler', 'cxx-compiler'.

**Comment by Aimeedeer** [comment]
https://github.com/brson/wasm-opt-rs/pull/125
