### ISSUE TITLE
Add arbitrary passes to PassRunner

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#12]
For this we need access to the PassRegistry.

- Make bindings for PassRegistry
  - getRegisteredNames
  - getPassDescription
  - isPassHidden

We'll need all of these for tests mostly.

- PassRunner::add - the one that takes a string argument

**Comment by Aimeedeer** [comment]
Added PassRegistry bindings.

Todo: 
- add tests
- add PassRunner::add

**Comment by Aimeedeer** [comment]
Todo: 
- add another example project that is more complex than the hello-world example

**Comment by Aimeedeer** [comment]
> 

added multisig.wasm for tests

**Comment by Aimeedeer** [comment]
done
