### ISSUE TITLE
CLI version prints incorrectly

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#131]
When installed from cargo I see this:

```
$ wasm-opt --version
wasm-opt version 111 ()
```

Binaryen looks like

```
$ ~/binaryen-version_108/bin/wasm-opt  --version
wasm-opt version 108 (version_108)
```

Probably this is because we are using the same logic to pull out the git tag and I hadn't tagged the release. I am also using a different tagging scheme.

I am not sure the solution to this off hand, whether we should reproduce exactly the string that Binaryen uses or not.

**Comment by Aimeedeer** [comment]
fixed https://github.com/brson/wasm-opt-rs/pull/133
