### ISSUE TITLE
Build failed with GCC-13

### ISSUE THREAD

**Issue by AurevoirXavier** [brson/wasm-opt-rs#147]
Check more detail here: https://substrate.stackexchange.com/questions/8540/compilation-errors-on-template-node

**Comment by brson** [comment]
Version 0.11.0, tracking Binaryen 111, is known to not build with GCC 13. Upgrading to wasm-opt 0.112.0, which tracks binaryen 112, should fix the issue.

This was also reported in https://github.com/brson/wasm-opt-rs/issues/143.

Substrate was upgraded to wasm-opt 112 in https://github.com/paritytech/substrate/pull/13574, so if you can upgrade substrate that should fix it.

If upgrading substrate is not possible, it may be possible to backport the binaryen fixes for gcc 13 to wasm-opt-rs 112, but I have not attempted to do so yet.
