### ISSUE TITLE
Figure out what to do about wasm features

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#18]
binaryen can be configured to work with post-mvp wasm features. At some point we probably need to support them in the API.

**Comment by brson** [comment]
We need to do this.

In the high level API:

- Add a `Feature` enum that contains all the features from C++, similar to `Pass`.
- Add a Features enum:

```
enum Features {
    Default,
    MvpOnly,
    All,
    Custom {
        enabled: HashSet<Feature>,
        disabled: HashSet<Fetature>,
    }
}
```

- Add OptimizationOptions field `features` of type `Features`.
- Add `enable_feature(Feature)` and `disable_feature(Feature)` builder methods
  - these will set the features field to `Custom`
- Add `mvp_features_only` and `all_features` builder methods.
- In the `run` method translate these to the base API and set the enabled/disabled features on the module

Base API and shims:

- Add a wrapper shim for `FeatureSet` containing an inner FeatureSet
- Add a `newFeatureSet` constructor that returns a unique_ptr to `FeatureSet::MVP`
- Add bindings for `setMVP` and `setAll`.
- Add bindings for `set`
- Add `Feature` c-like enum that exactly matches binaryen's `FeatureSet::Feature` enum
- Add shim method `Module::applyFeatures` that takes the enabled and disabled feature sets and does the same thing as OptimizationOptions.applyFeatures.

Tests:

- Test that base Feature enum has same values as C++ enums

**Comment by Aimeedeer** [comment]
done
