### ISSUE TITLE
Sanity check tests

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#23]
There are a number of places where we duplicate information in the Rust API from the C++ API. We need to have some tests that confirm these duplications continue to be correct as the project is maintained and binaryen is upgraded.

E.g. We have a duplicate `InliningOptions` struct that has a `Default` implementation. These default values should be the same as the default values in C++. We _could_ call C++ in the `Default` implementation to get them from C++, then convert from C++ to Rust, but I think the code will be cleaner if we just duplicate the default values and write tests to confirm them.

Here's how to do it:

- Add a C++ namespace to hold these tests, like `wasm_opt_tests`.
- Add a C++ function named `check_inlining_options_defaults` that accepts a `unique_ptr<InliningOptions>` and returns `bool`
- Construct a C++ `InliningOptions` and compare it to the one passed as an argument
- If they are not the same return `false`
- Add a Rust test named `test_inlining_options_defaults`
- Construct the Rust `InliningOptions`, convert it to the C++ `unique_ptr<InliningOptions>`
- Call the C++ function and assert it returns `true`.

In some cases, we need to test that the Rust side enumerates all possible values of something, e.g. pass names. 
In that specific case we can write a C++ function that returns all the passes in the `PassRegistry`, and the Rust test can check that we have an enum variant for all of them.

We need these types of tests for

- `InliningOptions` default values
- `PassOptions` default values
- The `Pass` enum should contain all the passes in the `PassRegistry`
- The `Features` enum should contain all the features in the C++ enum
- The Rust equivalents of `-Os` and `-Oz` produce the same optimize and shrink levels
- others tbd

**Comment by Aimeedeer** [comment]
Tests added:
- check_inlining_options_defaults
- `Pass` enum contain all the passes in the `PassRegistry`

**Comment by Aimeedeer** [comment]
added test check_pass_options_defaults
