### ISSUE TITLE
Convert ModuleReader ModuleWriter shims into wrapping classes

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#24]
These were the first two shims we wrote and they don't follow the better pattern we used for InliningOptions and PassOptions.

Instead of defining awkwardly-named free functions like ModuleReader_read, lets define our own ModuleReader in the wasm_shims namespace, that contains an inner wasm::ModuleReader, and convert the free functions to methods on the wrapper type.

**Comment by Aimeedeer** [comment]
done
