### ISSUE TITLE
Add constructors for OptimizationOptions

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#31]
There should be constructors that correspond to `-O1`, `-O2`, `-O3`, `-O4`, `-Os`, and `-Oz`. Possibly also `-O0` but that should be the same as `default`.

**Comment by Aimeedeer** [comment]
`optimization-options.h` shows the default optimize level = 2, default shrink level = 1. 
The default optimization passes equivalent to `-Os`.
`-O0` has both optimize level and shrink level set to 0.

I changed our default constructors for `OptimizeLevel` and `ShrinkLevel` to 2 and 1 respectively.
