### ISSUE TITLE
Fixes to config.h generation

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#32]
This code isn't quite right.

We need config.h to be correct even when there is no binaryen git repo to query. This will happen when wasm-opt-rs is published to crates.io.

These things should change:

- config.h should live in wasm-opt-sys/src, not in OUTPUT_DIR. That way it is part of the repo source code.
- If calling `git describe` fails then `get_project_version` should fail, not return an empty string.
- If `get_project_version` fails `create_config_header` should succeed, but not write `config.h`.

**Comment by brson** [comment]
The emitted header isn't correct either.

This is what the binaryen build system generates:

```
#define PROJECT_VERSION "109 (version_109-95-ge5c8bf665)"
```

This is what our header contains:

```
#define PROJECT_VERSION "version_109"
```

Binaryen's version number also seems to change based on whether it is being built from git or not. This is what my installed version of wasm-opt reports as --version:

```
wasm-opt version 108 (version_108)
```

That "108 (version_108)" is presumably the contents of PROJECT_VERSION.

I think we don't strictly need to have the git hash in our version the way binaryen does. If we can just make it look like "108 (version_108)" that would be fine.

If this gets too difficult to do dynamically we can just hard-code config.h.

We probably need some kind of test that we have the version correct, but it's going to be tough to write. We'll need to have some kind of integration tests that build the actual wasm-opt and compare its behavior against our own wasm-opt.

**Comment by Aimeedeer** [comment]
done
