### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#6]
We'll use GitHub actions.

Start with x86_64-unknown-linux-gnu

These are the ones we've promised:

- aarch64-apple-darwin
- aarch64-unknown-linux-gnu
- i686-pc-windows-msvc
- i686-unknown-linux-gnu
- x86_64-apple-darwin
- x86_64-pc-windows-msvc
- x86_64-unknown-linux-gnu

We might also want to add some for

- clang with libstdc++ on linux
- clang with libc++ on linux
- clang with mold linker on linux
- minimum rust version

**Comment by Aimeedeer** [comment]
CI currently working with ubuntu-20.04, macos-11, and windows-2019

**Comment by brson** [comment]
Test minimum C++ compiler versions. C++17 was supported in:

- gcc - 5,6, or 7
- clang - 3.9 or 4
- msvc - Visual Studio 2019

**Comment by brson** [comment]
Here is a ci config to cheat off of https://github.com/dtolnay/cxx/blob/master/.github/workflows/ci.yml

**Comment by brson** [comment]
We can support Rust 1.48 and should put it in our test matrix. This is the same version that the cxx crate supports.

**Comment by Aimeedeer** [comment]
The matrix includes
- macos-11
- windows-2019
- ubuntu-20.04 + gcc-7 / clang-7
- ubuntu-18.04 + clang-3.9 + rust: 1.48.0

**Comment by brson** [comment]
Big thing we're missing is arm builders.

**Comment by brson** [comment]
I'll open a new issue for arm builders.
