### ISSUE TITLE
Conformance tests

### ISSUE THREAD

**Issue by brson** [brson/wasm-opt-rs#69]
Add tests that the binaryen wasm-opt, rust wasm-opt CLI, and Command-based API all produce the same results. The output module and sourcemap should be checked that they are binary identical.

Some tests we need:

- input wasm, output wasm, no optimization args
- input wasm, output wasm, -Os, -Oz, -O0,1,2,3,4
- input wasm, output wat
- input wat, output wasm
- input wasm, output wat, no opt args
- input wasm, output wat, -Os
- input wat, output wasm, no opt args
- input wat, output wasm, -Os
- input wasm with sourcemap, output wasm without sourcemap, -Os
- input wasm with sourcemap, output wasm with sourcemap, -Os
- -O0 plus the inlining-with-opts pass
- -g (used by cargo-contract)
- -zero-filled-memory (used by cargo-contract)

**Comment by Aimeedeer** [comment]
done
