### ISSUE TITLE
`OptimizationOptions::debug_info` isn't functional

### ISSUE THREAD

**Issue by athei** [brson/wasm-opt-rs#81]
I am trying out [`OptimizationOptions::debug_info`](https://docs.rs/wasm-opt/0.0.1-preview.3/wasm_opt/struct.OptimizationOptions.html#method.debug_info) on `0.0.1-preview.3`. However, no matter whether I set it to `true` or `false` the `name` section is always removed.

**Comment by brson** [comment]
I suspect this is fixed on master. We have fixed many bugs since that
preview release and I expect to publish a finished create packaging
binaryen 110 within days.

**Comment by brson** [comment]
A new release is published. This should be fixed.

**Comment by brson** [comment]
Fixed.
