### ISSUE TITLE
Notes on the unsafe keyword

### ISSUE THREAD

**Issue by dtolnay** [brson/wasm-opt-rs#92]
https://github.com/brson/wasm-opt-rs/blob/aad563327f248190a17ad48de8e0a3f667b76597/notes.md#L721-L723

I think this is not the right mental model. The unsafe keyword means the programmer who is writing all those function signatures inside the extern block is on the hook for the unsafe responsibility of which ones to declare as `fn` vs `unsafe fn` according to their C++ semantics. In the extern block shown, the programmer has decided all these functions behave in a way that is safe to call from Rust. If there were no functions in the block that were made safe to call from Rust, the unsafe on the extern block would not be needed because there isn't anything the programmer is vouching for in that case.

**Comment by brson** [comment]
I have reworded this.
